apiVersion: 1

datasources:
  - name: Weather Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: weather
    user: weather
    secureJsonData:
      password: weather_dev_only
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
